name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g --legacy-peer-deps
      - name: Install Dependencies
        run: npm i --legacy-peer-deps
      - name: Build project
        run: npm run build
      - name: Echo keys
        run: echo "${{ env.SITE_ID }} ${{ env.NETLIFY_TOKEN }}"
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ env.SITE_ID }} \
            --auth ${{ env.NETLIFY_TOKEN }}
